// Shared defaults: loaded by the content script (manifest) and the options page.
// Domain lists are one domain per line; '#' starts a comment; subdomains are included.

// Pages you are BROWSING on which the extension does nothing.
// Domains are matched by host only (no paths), so entries are kept specific on purpose
// (e.g. www.amazon.com instead of amazon.com, so docs.aws.amazon.com keeps working).
const HLP_DEFAULT_EXCLUDED = [
  '# Social networks & messengers',
  'instagram.com',
  'facebook.com',
  'messenger.com',
  'linkedin.com',
  'x.com',
  'twitter.com',
  'threads.net',
  'tiktok.com',
  'snapchat.com',
  'pinterest.com',
  'tumblr.com',
  'whatsapp.com',
  'telegram.org',
  'discord.com',
  '# Banking & payments',
  'paypal.com',
  'stripe.com',
  'razorpay.com',
  'paytm.com',
  'phonepe.com',
  'wise.com',
  'hdfcbank.com',
  'icicibank.com',
  'axisbank.com',
  'kotak.com',
  'sbi.co.in',
  'onlinesbi.sbi',
  'chase.com',
  'bankofamerica.com',
  'wellsfargo.com',
  'americanexpress.com',
  '# Email, chat & video calls',
  'mail.google.com',
  'outlook.com',
  'outlook.live.com',
  'outlook.office.com',
  'outlook.office365.com',
  'mail.yahoo.com',
  'mail.proton.me',
  'slack.com',
  'teams.microsoft.com',
  'teams.live.com',
  'zoom.us',
  'meet.google.com',
  '# Video & music streaming',
  'youtube.com',
  'netflix.com',
  'twitch.tv',
  'primevideo.com',
  'hotstar.com',
  'disneyplus.com',
  'hulu.com',
  'spotify.com',
  '# Maps',
  'maps.google.com',
  '# Office, docs & project tools',
  'docs.google.com',
  'sheets.google.com',
  'slides.google.com',
  'drive.google.com',
  'calendar.google.com',
  'office.com',
  'onedrive.live.com',
  'sharepoint.com',
  'notion.so',
  'figma.com',
  'canva.com',
  'miro.com',
  'trello.com',
  'atlassian.net',
  'asana.com',
  'airtable.com',
  'linear.app',
  'clickup.com',
  'monday.com',
  '# Code hosting (GitHub etc. block framing anyway)',
  'github.com',
  'gitlab.com',
  'bitbucket.org',
  '# Cloud & admin consoles',
  'console.aws.amazon.com',
  'signin.aws.amazon.com',
  'console.cloud.google.com',
  'console.firebase.google.com',
  'portal.azure.com',
  'dash.cloudflare.com',
  'app.netlify.com',
  'cloud.digitalocean.com',
  '# Shopping',
  'www.amazon.com',
  'www.amazon.in',
  'flipkart.com',
  'myntra.com',
  'ebay.com',
  '# Login & single sign-on pages',
  'accounts.google.com',
  'login.microsoftonline.com',
  'login.live.com',
  'appleid.apple.com',
  'okta.com',
].join('\n');

// Link DESTINATIONS that never get a preview (deny-list mode): link shorteners and ad/tracking
// redirectors, whose "preview" would just fire the redirect or tracker.
const HLP_DEFAULT_DESTINATION_DENY = [
  '# Link shorteners & tracking redirects',
  't.co',
  'bit.ly',
  'lnkd.in',
  'goo.gl',
  'tinyurl.com',
  'ow.ly',
  'buff.ly',
  'fb.me',
  'amzn.to',
  'doubleclick.net',
  'googleadservices.com',
  'googlesyndication.com',
].join('\n');

const HLP_DEFAULTS = {
  enabled: true,
  delaySec: 5,
  size: 'medium',
  keepOnScreen: false,
  listMode: 'deny',
  domains: HLP_DEFAULT_DESTINATION_DENY, // link-destination list (deny/allow, see listMode)
  excludedSites: HLP_DEFAULT_EXCLUDED, // pages on which the extension does nothing
};
